Repository AGH-Narzedzia-Informatyczne/God-s-eye, pull requests merged in 2020-11, with the labels that each got.

#9 Struct
  main/struct.hpp
Labels: bug, help wanted

#13 Added testing autoconnection to open networks
  test/blink.ino
  test/defines.hpp
  test/serial.ino
  test/test.ino
  test/wifi.ino
Labels: enhancement

#18 New look with Bootstrap
  Web/app.js
  Web/controllers/authController.js
  Web/models/User.js
  Web/package-lock.json
  Web/public/dashboard.css
  Web/public/signin.css
  Web/public/styles.css
  Web/routes/authRoutes.js
  Web/views/index.ejs
  Web/views/login.ejs
  Web/views/partials/footer.ejs
  Web/views/partials/head.ejs
  Web/views/password.ejs
Labels: enhancement, improvement

#24 Testing Wi-Fi connection by sending HTTP POST request
  test/test.ino
  test/wifi.ino
Labels: enhancement

#26 Testing firmware
  test/custombtn.ino
  test/test.ino
Labels: enhancement
